version: '2'
services:
    kcm-app:
        image: kcm
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kcm-mysql:3306/kcm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://kcm-elasticsearch:9200
        ports:
            - 8080:8080
    kcm-mysql:
        extends:
            file: mysql.yml
            service: kcm-mysql
    kcm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kcm-elasticsearch
